//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyDirectoryDF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public Employee()
        {
            this.DirectoryEmployees = new HashSet<DirectoryEmployee>();
            this.PhoneLists = new HashSet<PhoneList>();
            this.EmployeeSkills = new HashSet<EmployeeSkill>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
     
        public Nullable<int> Ext { get; set; }
        [Required]
        [Range(1000000000, 9999999999, ErrorMessage = "Invalid Phone")]
        public string OfficePhone { get; set; }
        [Required]
        [Range(1000000000, 9999999999, ErrorMessage = "Invalid Phone")]
        public string CellPhone { get; set; }
        [Required]
        [Range(1000000000, 9999999999, ErrorMessage = "Invalid Phone")]
        public string HomePhone { get; set; }
    
        [DisplayFormat(DataFormatString = "{0:(###) ###-####}", ApplyFormatInEditMode = true)]
        public long OfficePhoneAsLong
        {
            get
            {
                return Convert.ToInt64(OfficePhone);
            }
        }
        [DisplayFormat(DataFormatString = "{0:(###) ###-####}", ApplyFormatInEditMode = true)]
        public long CellPhoneAsLong
        {
            get
            {
                return Convert.ToInt64(CellPhone);
            }
        }
        [DisplayFormat(DataFormatString = "{0:(###) ###-####}", ApplyFormatInEditMode = true)]
        public long HomePhoneAsLong
        {
            get
            {
                return Convert.ToInt64(HomePhone);
            }
        }
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }    
        public virtual ICollection<DirectoryEmployee> DirectoryEmployees { get; set; }
        public virtual ICollection<PhoneList> PhoneLists { get; set; }
        public virtual ICollection<EmployeeSkill> EmployeeSkills { get; set; }
    }
}
